"""premium + features + flags + site_admin

Revision ID: 1a1d8911c372
Revises: c6964e962603
Create Date: 2025-08-24 13:08:44.544875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1d8911c372'
down_revision: Union[str, Sequence[str], None] = 'c6964e962603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_key'), 'features', ['key'], unique=True)
    op.create_table('guild_feature_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'feature_id', name='uq_guild_feature')
    )
    op.create_index(op.f('ix_guild_feature_flags_feature_id'), 'guild_feature_flags', ['feature_id'], unique=False)
    op.create_index(op.f('ix_guild_feature_flags_guild_id'), 'guild_feature_flags', ['guild_id'], unique=False)
    op.create_table('premium_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'guild_id', name='uq_premium_user_guild')
    )
    op.create_index(op.f('ix_premium_memberships_guild_id'), 'premium_memberships', ['guild_id'], unique=False)
    op.create_index(op.f('ix_premium_memberships_user_id'), 'premium_memberships', ['user_id'], unique=False)
    # 1) ajouter la colonne avec un DEFAULT à false le temps de la migration
    op.add_column(
        "users",
        sa.Column("is_site_admin", sa.Boolean(), nullable=False, server_default=sa.text("false"))
    )
    # 2) retirer le DEFAULT pour le schéma final (optionnel mais propre)
    op.alter_column("users", "is_site_admin", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_site_admin')
    op.drop_index(op.f('ix_premium_memberships_user_id'), table_name='premium_memberships')
    op.drop_index(op.f('ix_premium_memberships_guild_id'), table_name='premium_memberships')
    op.drop_table('premium_memberships')
    op.drop_index(op.f('ix_guild_feature_flags_guild_id'), table_name='guild_feature_flags')
    op.drop_index(op.f('ix_guild_feature_flags_feature_id'), table_name='guild_feature_flags')
    op.drop_table('guild_feature_flags')
    op.drop_index(op.f('ix_features_key'), table_name='features')
    op.drop_table('features')
    # ### end Alembic commands ###
