"""add user.display_name

Revision ID: 4610304b1cc9
Revises: 5a4b4da3ccda
Create Date: 2025-08-24 12:49:17.040765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4610304b1cc9'
down_revision: Union[str, Sequence[str], None] = '5a4b4da3ccda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
